version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    ports:
      - "9200:9200"
    volumes:
      - '.\logs:/usr/share/elasticsearch/data'
    networks:
      logmetric:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      logmetric:

  ravendb:
    image: ravendb/ravendb
    ports:
      - 8080:8080
    volumes:
      - '.\db:/opt/RavenDB/Server/RavenData'
    networks:
      ravendb-net:


networks:
  ravendb-net:
    driver: 'bridge'

  logmetric:
    driver: 'bridge'
    